### ISSUE TITLE
Factorio Headless Snap Update to Version 1.1.30

### ISSUE THREAD

**Issue by j-pye** [predr/factorio-headless-snap#4]
The Snap is still locked to 1.1.27
https://snapcraft.io/factorio-headless

Current Stable Factorio Headless Release is 1.1.30
```
❯ wget -qO- "https://factorio.com/api/latest-releases"
{"experimental":{"alpha":"1.1.30","demo":"1.1.30","headless":"1.1.30"},"stable":{"alpha":"1.1.30","demo":"1.1.30","headless":"1.1.30"}}
```

It looks like the github action that performs the release hasn't been able to run since before 1.1.30 was released as stable. I believe this is due to repository inactivity on github. Updating the README or any file in the repository should allow the github action to run again.

**Comment by predr** [comment]
Hi, thanks for reporting. Released 1.1.30 update. It is done manually on Snapcraft site and not by Github action which is disabled. It is disabled because it was never properly tested and when v1.0 was being released and updated it looked like there wasn't going to be any more experimental builds and latest-releases api.
